# Generated by Django 3.0 on 2020-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessdetails',
            old_name='Webpage',
            new_name='webpage',
        ),
        migrations.AlterField(
            model_name='accessdetails',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
